var april = [
  {
    "vname": "101台北貓動物醫院",
    "vets": 5,
    "tiems": 4,
    "talk": 3,
    "target": 5,
    "cutomer": 4,
    "env": 5,
    "total": 26,
  },
  {
    "vname": "文藝獸醫院",
    "vets": 4,
    "tiems": 3,
    "talk": 3,
    "target": 4,
    "cutomer": 5,
    "env": 4,
    "total": 23,
  },
  {
    "vname": "東京頂尖動物醫院",
    "vets": 4,
    "tiems": 3,
    "talk": 2,
    "target": 4,
    "cutomer": 4,
    "env": 5,
    "total": 22,
  },
  {
    "vname": "中山動物醫院",
    "vets": 2,
    "tiems": 5,
    "talk": 3,
    "target": 0,
    "cutomer": 4,
    "env": 5,
    "total": 19,
  },
  {
    "vname": "小王子動物醫院",
    "vets": 4,
    "tiems": 2,
    "talk": 3,
    "target": 2,
    "cutomer": 3,
    "env": 5,
    "total": 19,
  },
  {
    "vname": "永信動物醫院",
    "vets": 5,
    "tiems": 2,
    "talk": 2,
    "target": 3,
    "cutomer": 3,
    "env": 4,
    "total": 19,
  },
  {
    "vname": "祐熙動物醫院",
    "vets": 5,
    "tiems": 2,
    "talk": 2,
    "target": 2,
    "cutomer": 3,
    "env": 4,
    "total": 18,
  },
  {
    "vname": "晨光動物醫院",
    "vets": 5,
    "tiems": 4,
    "talk": 1,
    "target": 2,
    "cutomer": 3,
    "env": 3,
    "total": 18,
  },
  {
    "vname": "曼哈頓動物醫院",
    "vets": 4,
    "tiems": 2,
    "talk": 3,
    "target": 1,
    "cutomer": 3,
    "env": 4,
    "total": 17,
  },
  {
    "vname": "上群動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 2,
    "target": 2,
    "cutomer": 3,
    "env": 5,
    "total": 16,
  },
  {
    "vname": "隆記動物醫院",
    "vets": 5,
    "tiems": 1,
    "talk": 1,
    "target": 3,
    "cutomer": 3,
    "env": 3,
    "total": 16,
  },
  {
    "vname": "太僕動物醫院(龍江院)",
    "vets": 4,
    "tiems": 4,
    "talk": 2,
    "target": 0,
    "cutomer": 3,
    "env": 3,
    "total": 16,
  },
  {
    "vname": "諾亞動物醫院",
    "vets": 3,
    "tiems": 3,
    "talk": 3,
    "target": 1,
    "cutomer": 2,
    "env": 3,
    "total": 15,
  },
  {
    "vname": "台欣動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 5,
    "env": 5,
    "total": 14,
  },
  {
    "vname": "米亞動物醫院",
    "vets": 5,
    "tiems": 3,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 5,
    "total": 14,
  },
  {
    "vname": "豐盛動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 2,
    "target": 2,
    "cutomer": 3,
    "env": 3,
    "total": 14,
  },
  {
    "vname": "恩典動物醫院",
    "vets": 3,
    "tiems": 4,
    "talk": 3,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 14,
  },
  {
    "vname": "德心動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 3,
    "env": 4,
    "total": 13,
  },
  {
    "vname": "路米動物醫院",
    "vets": 2,
    "tiems": 2,
    "talk": 3,
    "target": 0,
    "cutomer": 2,
    "env": 4,
    "total": 13,
  },
  {
    "vname": "日健動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 2,
    "target": 1,
    "cutomer": 4,
    "env": 3,
    "total": 13,
  },
  {
    "vname": "成功獸醫院",
    "vets": 4,
    "tiems": 4,
    "talk": 1,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 13,
  },
  {
    "vname": "傑翔動物醫院",
    "vets": 4,
    "tiems": 3,
    "talk": 1,
    "target": 1,
    "cutomer": 0,
    "env": 3,
    "total": 12,
  },
  {
    "vname": "長沁動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 2,
    "env": 4,
    "total": 11,
  },
  {
    "vname": "興泰動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 10,
  },
  {
    "vname": "美加璦動物醫院",
    "vets": 3,
    "tiems": 2,
    "talk": 1,
    "target": 1,
    "cutomer": 0,
    "env": 3,
    "total": 10,
  },
  {
    "vname": "慈愛動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 3,
    "target": 0,
    "cutomer": 3,
    "env": 2,
    "total": 10,
  },
  {
    "vname": "貝恩動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 9,
  },
  {
    "vname": "梁動物內科醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 3,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "金旺動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "澤禾動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "廣慈動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "大晶獸醫院",
    "vets": 3,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "人人愛動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 3,
    "env": 2,
    "total": 9,
  },
  {
    "vname": "泰山動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 2,
    "cutomer": 0,
    "env": 2,
    "total": 9,
  },
  {
    "vname": "澄諾動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 8,
  },
  {
    "vname": "嘉慶動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 8,
  },
  {
    "vname": "吉米動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 8,
  },
  {
    "vname": "不萊梅特殊寵物專科醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "長宏獸醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "東宏獸醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "旺竹動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "正安動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 1,
    "env": 2,
    "total": 8,
  },
  {
    "vname": "興安動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 2,
    "cutomer": 0,
    "env": 2,
    "total": 8,
  },
  {
    "vname": "皇家動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 1,
    "env": 2,
    "total": 7,
  },
  {
    "vname": "華遠獸醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 7,
  },
  {
    "vname": "弘安動物醫院",
    "vets": 2,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 7,
  },
  {
    "vname": "新亞動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 6,
  },
  {
    "vname": "台灣動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "三民動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "良醫動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "全陽動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "戴瑩乾動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 5,
  },
  {
    "vname": "吉林動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 1,
    "total": 4,
  },
];

var july = [
  {
    "vname": "101台北貓動物醫院",
    "vets": 5,
    "tiems": 5,
    "talk": 3,
    "target": 5,
    "cutomer": 4,
    "env": 5,
    "total": 27,
  },
  {
    "vname": "永信動物醫院",
    "vets": 5,
    "tiems": 2,
    "talk": 2,
    "target": 3,
    "cutomer": 3,
    "env": 4,
    "total": 19,
  },
  {
    "vname": "祐熙動物醫院",
    "vets": 5,
    "tiems": 2,
    "talk": 2,
    "target": 2,
    "cutomer": 3,
    "env": 4,
    "total": 18,
  },
  {
    "vname": "晨光動物醫院",
    "vets": 5,
    "tiems": 4,
    "talk": 1,
    "target": 2,
    "cutomer": 3,
    "env": 3,
    "total": 18,
  },
  {
    "vname": "米亞動物醫院",
    "vets": 5,
    "tiems": 3,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 5,
    "total": 14,
  },
  {
    "vname": "隆記動物醫院",
    "vets": 5,
    "tiems": 5,
    "talk": 1,
    "target": 3,
    "cutomer": 3,
    "env": 3,
    "total": 20,
  },
  {
    "vname": "小王子動物醫院",
    "vets": 4,
    "tiems": 2,
    "talk": 3,
    "target": 2,
    "cutomer": 3,
    "env": 5,
    "total": 19,
  },
  {
    "vname": "曼哈頓動物醫院",
    "vets": 4,
    "tiems": 2,
    "talk": 3,
    "target": 1,
    "cutomer": 3,
    "env": 4,
    "total": 17,
  },
  {
    "vname": "文藝獸醫院",
    "vets": 4,
    "tiems": 5,
    "talk": 3,
    "target": 4,
    "cutomer": 5,
    "env": 4,
    "total": 25,
  },
  {
    "vname": "太僕動物醫院(龍江院)",
    "vets": 4,
    "tiems": 4,
    "talk": 2,
    "target": 0,
    "cutomer": 3,
    "env": 3,
    "total": 16,
  },
  {
    "vname": "東京頂尖動物醫院",
    "vets": 4,
    "tiems": 5,
    "talk": 2,
    "target": 4,
    "cutomer": 4,
    "env": 5,
    "total": 24,
  },
  {
    "vname": "傑翔動物醫院",
    "vets": 4,
    "tiems": 3,
    "talk": 1,
    "target": 1,
    "cutomer": 0,
    "env": 3,
    "total": 12,
  },
  {
    "vname": "成功獸醫院",
    "vets": 4,
    "tiems": 4,
    "talk": 1,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 13,
  },
  {
    "vname": "上群動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 2,
    "target": 2,
    "cutomer": 3,
    "env": 5,
    "total": 16,
  },
  {
    "vname": "美加璦動物醫院",
    "vets": 3,
    "tiems": 2,
    "talk": 1,
    "target": 1,
    "cutomer": 0,
    "env": 3,
    "total": 10,
  },
  {
    "vname": "德心動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 3,
    "env": 4,
    "total": 13,
  },
  {
    "vname": "泰山動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 2,
    "cutomer": 0,
    "env": 2,
    "total": 9,
  },
  {
    "vname": "豐盛動物醫院",
    "vets": 3,
    "tiems": 3,
    "talk": 3,
    "target": 2,
    "cutomer": 3,
    "env": 3,
    "total": 17,
  },
  {
    "vname": "恩典動物醫院",
    "vets": 3,
    "tiems": 5,
    "talk": 3,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 15,
  },
  {
    "vname": "大晶獸醫院",
    "vets": 3,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "諾亞動物醫院",
    "vets": 3,
    "tiems": 3,
    "talk": 3,
    "target": 1,
    "cutomer": 2,
    "env": 3,
    "total": 15,
  },
  {
    "vname": "貝恩動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 9,
  },
  {
    "vname": "東宏獸醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "正安動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 1,
    "env": 2,
    "total": 8,
  },
  {
    "vname": "華遠獸醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 7,
  },
  {
    "vname": "沐樂動物醫院",
    "vets": 3,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 9,
  },
  {
    "vname": "中山動物醫院",
    "vets": 2,
    "tiems": 5,
    "talk": 3,
    "target": 0,
    "cutomer": 4,
    "env": 5,
    "total": 19,
  },
  {
    "vname": "台欣動物醫院",
    "vets": 3,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 5,
    "env": 5,
    "total": 16,
  },
  {
    "vname": "路米動物醫院",
    "vets": 3,
    "tiems": 3,
    "talk": 3,
    "target": 0,
    "cutomer": 2,
    "env": 4,
    "total": 15,
  },
  {
    "vname": "日健動物醫院",
    "vets": 2,
    "tiems": 2,
    "talk": 2,
    "target": 1,
    "cutomer": 4,
    "env": 3,
    "total": 14,
  },
  {
    "vname": "興泰動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 10,
  },
  {
    "vname": "金旺動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "澤禾動物醫院",
    "vets": 2,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 11,
  },
  {
    "vname": "人人愛動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 3,
    "env": 2,
    "total": 9,
  },
  {
    "vname": "澄諾動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 8,
  },
  {
    "vname": "嘉慶動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 8,
  },
  {
    "vname": "長宏獸醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "興安動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 2,
    "cutomer": 0,
    "env": 2,
    "total": 8,
  },
  {
    "vname": "弘安動物醫院",
    "vets": 2,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 7,
  },
  {
    "vname": "台灣動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "三民動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "良醫動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "全陽動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "欣旺動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
  {
    "vname": "長沁動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 2,
    "env": 4,
    "total": 11,
  },
  {
    "vname": "慈愛動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 3,
    "target": 0,
    "cutomer": 3,
    "env": 2,
    "total": 10,
  },
  {
    "vname": "梁動物內科醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 3,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "廣慈動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 1,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "吉米動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 8,
  },
  {
    "vname": "不萊梅特殊寵物專科醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "旺竹動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "皇家動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 1,
    "env": 2,
    "total": 7,
  },
  {
    "vname": "新亞動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 6,
  },
  {
    "vname": "戴瑩乾動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 5,
  },
  {
    "vname": "吉林動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 1,
    "total": 4,
  },
  {
    "vname": "恩加動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 4,
    "env": 3,
    "total": 10,
  },
  {
    "vname": "永春動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 6,
  },
  {
    "vname": "寵物中西整合醫療-和動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 7,
  },
  {
    "vname": "敦化動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 6,
  },
  {
    "vname": "敦品動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 7,
  },
  {
    "vname": "五洲動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 1,
    "cutomer": 0,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "集英動物醫院",
    "vets": 0,
    "tiems": 1,
    "talk": 0,
    "target": 0,
    "cutomer": 0,
    "env": 0,
    "total": 1,
  },
  {
    "vname": "凱揚動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 4,
    "total": 8,
  },
  {
    "vname": "恩孺動物診所",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 5,
    "env": 3,
    "total": 11,
  },
  {
    "vname": "瀚生動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 1,
    "cutomer": 1,
    "env": 3,
    "total": 8,
  },
  {
    "vname": "極光動物醫院",
    "vets": 1,
    "tiems": 2,
    "talk": 2,
    "target": 0,
    "cutomer": 2,
    "env": 3,
    "total": 10,
  },
  {
    "vname": "富康動物醫院",
    "vets": 4,
    "tiems": 1,
    "talk": 1,
    "target": 3,
    "cutomer": 2,
    "env": 3,
    "total": 14,
  },
  {
    "vname": "維東尼動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 7,
  },
  {
    "vname": "欣欣動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 5,
  },
  {
    "vname": "星辰動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 2,
    "target": 0,
    "cutomer": 0,
    "env": 3,
    "total": 7,
  },
  {
    "vname": "專心動物醫院",
    "vets": 1,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 3,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "萬國家畜醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 2,
    "cutomer": 0,
    "env": 3,
    "total": 9,
  },
  {
    "vname": "佑仁動物醫院",
    "vets": 2,
    "tiems": 1,
    "talk": 1,
    "target": 0,
    "cutomer": 0,
    "env": 2,
    "total": 6,
  },
];

var temp = [];
for (let i = 0; i < july.length; i++) {
  const julyTerm = july[i];
  let state = 0;
  for (let j = 0; j < april.length; j++) {
    const aprilTerm = april[j];
    if (aprilTerm.vname == julyTerm.vname) {
      state++;
    }
  }

  if (state == 0) {
    temp.push(julyTerm);
  }
}

console.log(temp.map((t) => t.vname).join("\n"));
